### ISSUE TITLE
Tips on using demo_patch ?

### ISSUE THREAD

**Issue by hubhubhang** [flatironinstitute/CaImAn-MATLAB#80]
Dear developer,

I would like to clarify if the "K" in "demo_patches.m" means the "number of components to be found in each patch" or "total number of components to be found in the total field of view "?

Also, from your experience, do you know what is the ideal ratio of patch size to total field of view size for optimal accuracy? I am wondering if the program performs the signal extraction and calcium model fitting in a spatially local manner (i.e. the result obtained from each patch is independent of the signal in other patches, for example, does the noise in one patch affect the result in other patch?) Also, I wonder if it's temporally local as well.

Thank you.

**Comment by epnev** [comment]
@hubhubhang The number K refers to the number of components per patch. This is not uniform in all patches so it's better to set a value that would capture the parts of the FOV with higher density and then reject false positives during components evaluation. 

The size of the patch is not that critical as long as the number of components is set to a value that could capture the components in each per patch. You want each patch to be small enough so you benefit from parallelization and non-uniformities in the FOV but not too small, because otherwise you can end up overfitting the neuropil signal for each patch and over-fragment your FOV.

The algorithm extracts information in a spatially local (but temporally global) manner. Please consult our [preprint](https://www.biorxiv.org/content/early/2018/06/05/339564) for more details.
