### ISSUE TITLE
what's the difference between DF/F extracted by extract_DF_F.m and plot_components_GUI.m ?

### ISSUE THREAD

**Issue by chunyueli** [flatironinstitute/CaImAn-MATLAB#85]
Thanks very much for your code! I'm using demo_script.m to process my 2p calcium data. I'm confused about extract_DF_F.m and plot_components_GUI.m function. The extract_DF_F.m extracts calcium DF/F signals for each ROI component. Function plot_components_GUI.m calls extract_DF_F.m in line 50, but only calculate Df, and it calculates raw and inferred calcium DF/F using Y_r(i,:)/Df(i) and C(i,:)/Df(i) in line 158-160. Are the DF/F extracted by extract_DF_F.m and plot_components_GUI.m the same? Moreover, I use the Gcamp6s indicator and set options.decay_time as 0.6s. The raw and inferred calcium DF/F showed by plot_components_GUI.m are not very similar. Is it normal? What's the best decay_time value for Gcamp6s? Thanks very much!

**Comment by epnev** [comment]
@chunyueli When I run the `demo_script` on the default demo file the traces look identical to me. Do you see the same behavior?
Also, what is the value of `options.df_window`?

**Comment by chunyueli** [comment]
Thanks very much for your help! 

The raw and inferred Df/f looks identical on the default demo. However, my result is not like this. I attached a figure that obtained on my Gcamp6s data. The options.decay_time is set as 0.6s, and df_window is empty. 
![capture](https://user-images.githubusercontent.com/16187697/48597229-98576d00-e997-11e8-914a-ec7b985cdd94.PNG)

Looking forward to your reply! Thanks a lot!

**Comment by epnev** [comment]
@chunyueli Is this what `plot_components_GUI.m` produces? If so, then the two traces should be different because the red is deconvolved activity and the blue is not. To modify the time constant try setting its multiplicative factor `options.fudge_factor` to a smaller than 1 value, e.g., 0.95. 

You also might want to set `options.bas_nonneg = false` since I see your traces can cross zero.

**Comment by chunyueli** [comment]
@epnev Thanks very much for your help!
I'm a little confused. I read your paper published in 2016 and also the documentation about this code. However, because of my poor mathematical background, maybe I misunderstand your paper. I thought the deconvolved activity was the inferred calcium event caused by intracellular electrical activity. If so, the deconvolved activity should be similar to raw DF/F (the blue signal; I set options.plot_df=1). This is also shown in your default demo file. I show the result below.

![demofile](https://user-images.githubusercontent.com/16187697/48634111-d25c5980-e9ff-11e8-898a-5cb6f9d0b742.png)
But in my results, the baseline seems not right.

Looking forward to your reply! Your help is greatly appreciated!

**Comment by epnev** [comment]
@chunyueli They are not the same.
The blue trace corresponds to the *demixed* fluorescence. This is the fluorescence for each component after the activity of all other overlapping neurons and background has been subtracted. There are no dynamics assumptions for this trace. On the code this corresponds to the variable `C+YrA`.
The red trace corresponds to the demixed *and deconvolved* trace for each component. This is the demixed trace as before with the additional condition that each trace needs to follow the dynamics of the calcium indicator so that every transient can be interpreted as deconvolved neural activity.

**Comment by chunyueli** [comment]
@epnev 
Thanks for your quick reply!
I understand your code better now! Thanks a lot!

**Comment by epnev** [comment]
@chunyueli you're welcome.
