### ISSUE TITLE
Error run_pipeline.m -- sizY?

### ISSUE THREAD

**Issue by akim5651** [flatironinstitute/CaImAn-MATLAB#87]
Hi there,

I've been trying to run .avi files from UCLA miniscope recordings through run_pipline.m, and have been encountering this error:

Undefined function or variable 'sizY'.

Error in normcorre_batch_even (line 68)
nd = length(sizY)-1;                          % determine whether imaging is 2d or 3d

Error in run_pipeline (line 36)
        [M,shifts,template,options_mc,col_shift] = normcorre_batch_even(fullname,options_mc,template);

This occurs when when I'm trying to run the 'motion correct' module 
> %% motion correct (and save registered h5 files as 2d matrices (to be used in the end)

Would appreciate your help!

**Comment by epnev** [comment]
@akim5651 

You will need to motion correct the `.avi` separately and save as `tif` or `h5` files, since a two step process is needed for miniscope datasets. Check the script [`demo_1p_low_RAM`](https://github.com/flatironinstitute/NoRMCorre/blob/master/demo_1p_low_RAM.m) on how to do this. After this you can use the `run_pipeline` script with the motion correction step turned off. However note that `CaImAn-MATLAB` is not meant to be used in miniscope data; and you can use the CNMF_E package instead or the python implementation of [`CaImAn`](https://github.com/flatironinstitute/CaImAn).

**Comment by akim5651** [comment]
Eftychios, thank you for the response. Will give that a try ASAP.
