### ISSUE TITLE
DEMO_pipeline

### ISSUE THREAD

**Issue by Mocambo90** [flatironinstitute/CaImAn-MATLAB#91]
Hi, I am trying to use caiman on Windows 10 with Matlab. My PC has a RAM of 8Gb.
Running demo_pipeline.mlx I am experiencing the following errors:

"Error using parallel.FevalFuture/fetchNext (line 217)"
The Function evaluation completed with an error.

Error in run_CNMF_patches (line 122)
            [idx, value] = fetchNext(future_results);

Thank you

**Comment by epnev** [comment]
@Mocambo90 The folder with the live scripts is somewhat outdated. Do you get the same error message if you use the `demo_pipeline.m` file?

**Comment by Mocambo90** [comment]
Hello,
First, I would like to thank you for your reply.
I have the same error also with the demo_pipeline.m!
Thanks

Il giorno mar 19 mar 2019 alle ore 03:09 eftychios pnevmatikakis <
notifications@github.com> ha scritto:

**Comment by epnev** [comment]
@Mocambo90 Sorry, I meant the script `run_pipeline.m`.
Can you change `parfeval` to `feval` in [line 118 of `run_CNMF_patches`](https://github.com/flatironinstitute/CaImAn-MATLAB/blob/master/run_CNMF_patches.m#L118) and run again? If you encounter an error please paste the entire error log.

**Comment by Mocambo90** [comment]
Hi, I tried but unfortunately the following errors occurred:

>> run_pipeline
Registering the first 200 frames just to obtain a good template......done.
Template initialization complete.  Now registering all the frames with new
template.
1200 out of 1200 frames registered, iteration 1 out of 1..starting
resampling
Elapsed time is 2.302807 seconds.


*Error using run_CNMF_patches>process_patch_objectToo many input arguments.*





*Error in run_CNMF_patches (line 119)        future_results(i) =
feval(@process_patch_object, 1, Yp, F_dark, K, p, tau, options);Error in
run_pipeline (line 127)[A,b,C,f,S,P,RESULTS,YrA] =
run_CNMF_patches(data.Y,K,patches,tau,0,options);  % do not perform
deconvolution here since*


Il giorno mar 19 mar 2019 alle ore 17:17 eftychios pnevmatikakis <
notifications@github.com> ha scritto:

**Comment by epnev** [comment]
@Mocambo90 Sorry, you'll also need to remove the input entry "1", i.e. have line 118 as:

```
future_results(i) = feval(@process_patch_object, Yp, F_dark, K, p, tau, options);
```
What error does this process give?

**Comment by Mocambo90** [comment]
Hello,
It gives me the following error:
[image: image.png]
Thanks again

Il giorno mar 19 mar 2019 alle ore 21:33 eftychios pnevmatikakis <
notifications@github.com> ha scritto:

**Comment by Mocambo90** [comment]
Hello,
It gives me the following error:

"**Undefined function 'fetchNext' for input arguments of type 'CNMF'.

Error in run_CNMF_patches (line 122)
        [idx, value] = fetchNext(future_results);

Error in run_pipeline (line 127)
[A,b,C,f,S,P,RESULTS,YrA] = run_CNMF_patches(data.Y,K,patches,tau,0,options);  % do not perform deconvolution here sinc here"
Thanks again

**Comment by epnev** [comment]
hmm, do you have the parallel computing toolbox?

**Comment by Mocambo90** [comment]
Yes!

Il giorno mer 20 mar 2019 alle ore 12:27 eftychios pnevmatikakis <
notifications@github.com> ha scritto:

**Comment by epnev** [comment]
@Mocambo90 I believe that your error might be caused by the limited RAM you have. Please revert the changes I suggested and try the following:

Instead of passing the argument `data.Y` in the `run_CNMF_patches` function pass just `data`:
`[A,b,C,f,S,P,RESULTS,YrA] = run_CNMF_patches(data,K,patches,tau,0,options)`
This should use the memory mapped file and hopefully consume less memory.

**Comment by 674067482** [comment]
Hello, I ran the 'run_pipeline.m' on Linux. Our input is a 2048*2048*2998 hdf5 file.  All parameters was default except 'fr' was set to be 2.  The complete error log list below:
>> run_pipeline
Starting parallel pool (parpool) using the 'local' profile ...
connected to 12 workers.
Registering the first 200 frames just to obtain a good template......done. 
Template initialization complete.  Now registering all the frames with new template. 
200 out of 2998 frames registered, iteration 1 out of 1. 
400 out of 2998 frames registered, iteration 1 out of 1. 
600 out of 2998 frames registered, iteration 1 out of 1. 
800 out of 2998 frames registered, iteration 1 out of 1. 
1000 out of 2998 frames registered, iteration 1 out of 1. 
1200 out of 2998 frames registered, iteration 1 out of 1. 
1400 out of 2998 frames registered, iteration 1 out of 1. 
1600 out of 2998 frames registered, iteration 1 out of 1. 
1800 out of 2998 frames registered, iteration 1 out of 1. 
2000 out of 2998 frames registered, iteration 1 out of 1. 
2200 out of 2998 frames registered, iteration 1 out of 1. 
2400 out of 2998 frames registered, iteration 1 out of 1. 
2600 out of 2998 frames registered, iteration 1 out of 1. 
2800 out of 2998 frames registered, iteration 1 out of 1. 
2998 out of 2998 frames registered, iteration 1 out of 1..No downsampling is performed 
No downsampling is performed 
Elapsed time is 1300.522506 seconds.
Error using parallel.FevalFuture/fetchNext (line 217)
The function evaluation completed with an error.

Error in run_CNMF_patches (line 121)
        [idx, value] = fetchNext(future_results);

Error in run_pipeline (line 136)
[A,b,C,f,S,P,RESULTS,YrA] = run_CNMF_patches(data.Y,K,patches,tau,0,options);  % do not perform deconvolution here since

Caused by:
    Error using images.internal.morphop>ParseInputs (line 154)
    Expected input number 1, IM, to be non-NaN.

Thanks for your help!
